LDLIBS = -lpthread

zad2a: zad2a1.c zad2a2.c zad2a3.c zad2a4.c zad2a5.c
	gcc -Wall -g -pedantic zad2a1.c $(LDLIBS) -o zad2a1
	gcc -Wall -g -pedantic zad2a2.c $(LDLIBS) -o zad2a2
	gcc -Wall -g -pedantic zad2a3.c $(LDLIBS) -o zad2a3
	gcc -Wall -g -pedantic zad2a4.c $(LDLIBS) -o zad2a4
	gcc -Wall -g -pedantic zad2a5.c $(LDLIBS) -o zad2a5
zad2b: zad2b.c
	gcc -Wall -g -pedantic zad2b.c $(LDLIBS) -o zad2b
clean: 
	rm zad2a1
	rm zad2a2
	rm zad2a3
	rm zad2a4
	rm zad2a5

