
testowy: testowy.c
	gcc testowy.c -o testowy

testowy2: testowy2.c
	gcc testowy2.c -o testowy2

withLimits: testowy2 testowy
	gcc withLimits.c -o withLimits

c:
	rm testowy	
	rm testowy2
	rm withLimits
