LDLIBS = -lpthread , -pthread

zad1a: zad1a.c
	gcc -Wall -g -pedantic zad1a.c -lpthread -pthread -o zad1a
	

zad1b: zad1b.c
	gcc -Wall -g -pedantic zad1b.c -lpthread -pthread -o zad1b

all: zad1a.c zad1b.c
	gcc -Wall -g -pedantic zad1a.c -lpthread -pthread -o zad1a
	gcc -Wall -g -pedantic zad1b.c -lpthread -pthread -o zad1b

clean: 
	rm zad1a
	rm zad1b

